import{a as h,S as g,i as d}from"./assets/vendor-BwXjtuc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function m(s,t=1){return await h.get(`https://pixabay.com/api/?q=${s}&image_type=photo&orientation=horizontal&safesearch=true&key=47380819-2a2ad5e165b633e18b6fd0fd3`,{params:{page:t,per_page:15}})}function u(s){return s.map(({webformatURL:t,largeImageURL:n,tags:r,likes:e,views:o,comments:i,downloads:f})=>`<li class="list-item" >
  <a href="${n}" alt="${r}" title=""/>
    <img src="${t}" alt="${r}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${o}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${i}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${f}</span></p>
  </div></a>
</li>`).join("")}const y=new g(".list-js a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),L=document.querySelector(".form-js"),c=document.querySelector(".list-js"),p=document.querySelector(".loader"),l=document.querySelector(".js-load-btn");L.addEventListener("submit",b);l.addEventListener("click",P);let a=1;function b(s){s.preventDefault();const{picture:t}=s.target.elements,n=t.value.trim();if(c.innerHTML="",!n||n===" "){d.show({title:":(",message:"Please add request!",position:"center",color:"red"}),c.innerHTML=":(";return}p.classList.remove("hidden"),l.classList.replace("more-btn","hidden"),m(n,a).then(({data:{hits:r}})=>{a=1,console.log(a),r.length?(c.innerHTML=u(r),y.refresh(),l.classList.replace("hidden","more-btn")):(d.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}),c.innerHTML="<h1>Ooops... 👻</h1>",l.classList.replace("more-btn","hidden"))}).catch(r=>{console.log(r.message),d.show({title:"X",message:`${r.message}`,position:"center",color:"red"})}).finally(()=>{t.value="",p.classList.add("hidden")})}async function P(){a+=1,console.log(a);try{const{data:{hits:s,totalHits:t}}=await m(a);console.log(s,t),c.insertAdjacentHTML("beforeend",u(s));let n=Math.round(t/s.length);(a>=n||!t)&&(l.classList.replace("more-btn","hidden"),d.show({title:"X",message:"We're sorry, but you've reached the end of search results.",position:"center",color:"red"}))}catch(s){console.log(s.message)}}
//# sourceMappingURL=index.js.map
