import{a as y,S as L,i as d}from"./assets/vendor-BwXjtuc1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function t(e){if(e.ep)return;e.ep=!0;const i=a(e);fetch(e.href,i)}})();async function u(s,o){return await y.get(`https://pixabay.com/api/?q=${s}&image_type=photo&orientation=horizontal&safesearch=true&key=47380819-2a2ad5e165b633e18b6fd0fd3`,{params:{page:o,per_page:15}})}function f(s){return s.map(({webformatURL:o,largeImageURL:a,tags:t,likes:e,views:i,comments:l,downloads:g})=>`<li class="list-item" >
  <a href="${a}" alt="${t}" title=""/>
    <img src="${o}" alt="${t}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${i}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${l}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${g}</span></p>
  </div></a>
</li>`).join("")}const h=new L(".list-js a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),b=document.querySelector(".form-js"),c=document.querySelector(".list-js"),p=document.querySelector(".loader"),r=document.querySelector(".js-load-btn");b.addEventListener("submit",w);r.addEventListener("click",P);let n=1,m=1;function w(s){s.preventDefault();const{picture:o}=s.target.elements,a=o.value.trim();if(c.innerHTML="",!a||a===" "){d.show({title:":(",message:"Please add request!",position:"center",color:"red"}),c.innerHTML=":(";return}n=1,p.classList.remove("hidden"),r.classList.replace("more-btn","hidden"),u(a,n).then(({data:{hits:t,totalHits:e}})=>{m=Math.ceil(e/t.length),console.log(n),t.length?(c.innerHTML=f(t),h.refresh(),n>=m&&r.classList.replace("more-btn","hidden"),r.classList.replace("hidden","more-btn")):(d.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}),c.innerHTML="<h1>Ooops... 👻</h1>")}).catch(t=>{console.log(t.message),d.show({title:"X",message:`${t.message}`,position:"center",color:"red"})}).finally(()=>{o.value="",p.classList.add("hidden")})}async function P(){n+=1,console.log(n),r.disabled=!0;try{const{data:{hits:s,totalHits:o}}=await u(n);c.insertAdjacentHTML("beforeend",f(s)),m=Math.ceil(o/s.length),console.log(m),(n>=m||!o)&&(r.classList.replace("more-btn","hidden"),d.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}));const t=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"}),h.refresh()}catch(s){console.log(s.message),d.show({title:"X",message:`${s.message}`,position:"center",color:"red"})}finally{r.disabled=!1}}
//# sourceMappingURL=index.js.map
